export default {
    'task_manager': 'Task manager',
    'login': 'Login',
    'loading_n_seconds_left': n => `Loading... (${n} second${n % 10 === 1 ? '' : 's'} left)`,
    'email': 'E-mail',
    'somebody_email': 'somebody@gmail.com',
    'password': 'Password',
    'to_login': 'Log in',
    'to_register': 'Register',
    'no_account_question': 'No account?',
    'to_log_out': 'Log out',
    'registration': 'Registration',
    'repeat_password': 'Repeat password',
    'already_have_account_question': 'Have got an account?',
    'editing': 'Editing',
    'task_name': 'Task name',
    'my_task': 'My task',
    'deadline': 'Deadline',
    'important_task': 'Important task',
    'cancel': 'Cancel',
    'to_save': 'Save',
    'ru': 'Russian',
    'en': 'English',
};
